version: "3"
services:
  frontend_server:
    image: hyeeeeejin/condibook-front:0.0.1
    restart: "on-failure"
    ports:
      - 80:80
    networks:
      - condibook

  backend_server:
    image: hyeeeeejin/condibook-back:0.0.1
    restart: "on-failure"
    ports:
      - 5001:5001
    networks:
      - condibook

  redis_server:
    image: "redis"
    networks:
      - condibook

networks:
  condibook:
